### ISSUE TITLE
Верстка блока "прайс-лист"

### ISSUE THREAD

**Issue by artembeloglazov** [rg1ru/obsada-front#23]
- [x] у Саши взять перечень цен
- [x] заменить картинки и поменять их цвета "Перевозок"

Взять за основу "иконки" с "Перевозок":

**Текст. с ценами:** чистые клееные обсады от 340 ₽/пог.м
**Текст про гарантию**: Гарантия 3 года

<img width="945" alt="image" src="https://user-images.githubusercontent.com/861680/40886597-a410384c-6743-11e8-937c-c26823d31808.png">

**Текст для тултипа**: После выезда нашего специалиста на объект цена может измениться
<img width="631" alt="image" src="https://user-images.githubusercontent.com/861680/40886642-8bcb5f68-6744-11e8-9caf-d9d84e626154.png">

**Comment by artembeloglazov** [comment]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/861680/40887631-454d755c-6754-11e8-8ae2-8e1e8ec99474.png">

**Comment by artembeloglazov** [comment]
### Передвинуть иконку "Гарантии"

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/861680/40887654-881891c8-6754-11e8-94d8-f3a5cdd0df75.png">

**Comment by artembeloglazov** [comment]
- [ ] исправить ошибку «Не показывается «?» во втором блоке в мобильной версии»

![6da30d4f-8af8-4c70-b182-52874a7677fa](https://user-images.githubusercontent.com/861680/41000810-d3da6716-6917-11e8-87f0-3134ecb85596.jpeg)

**Comment by shocer74** [comment]
В каком смысле не показывается или сделать его круглей ?

**Comment by shocer74** [comment]
Или подвинуть его ниже где на скрине отмечено красным кругом ?

**Comment by artembeloglazov** [comment]
отсутствует всплывающий тултип, просто надо его добавить как и у первой цены
