### ISSUE TITLE
Добавить отступы 

### ISSUE THREAD

**Issue by artembeloglazov** [rg1ru/obsada-front#25]
## Добавить отступ для верхнего блока "Логотип/Контакты"

![img_20180529_221123](https://user-images.githubusercontent.com/861680/40685061-df46f3ac-639b-11e8-8ded-8836aa3deb63.jpg)

## Добавить отступ для нижнего блока "Рассчитать", чтобы была видна кнопка "Отправить"

<img width="457" alt="image" src="https://user-images.githubusercontent.com/861680/40687628-f8289724-63a3-11e8-924d-f912b59f6483.png">

**Comment by shocer74** [comment]
На каком розширение эти скриншоты ?

**Comment by artembeloglazov** [comment]
> На каком розширение эти скриншоты ?

разрешении?

**Comment by artembeloglazov** [comment]
первый скрин - не известно разрешение, второй - 640×1136

**Comment by artembeloglazov** [comment]
Кнопку калькулятора не видно

**Comment by shocer74** [comment]
Делаю отступ , а кнопка не видна. Ты там вроди должен был найти файлы настройки калькулятооа , а  то их нпт .

**Comment by artembeloglazov** [comment]
Да, забыл

**Comment by shocer74** [comment]
Дашь мне эти файлы , я окончил . Потратил чуть меньше часа

**Comment by artembeloglazov** [comment]
Файл `calculation.less`. Примерно я прикинул margin-bottom для `.calculation` равен 94px. Внимательно учти, что это исправление должно работать **только для мобильной версии**.


<img width="328" alt="image" src="https://user-images.githubusercontent.com/861680/40782052-c818e66c-64e6-11e8-8ad4-1d258333f4fd.png">

**Comment by shocer74** [comment]
Скоро буду дома , выполню эту задачу .

**Comment by shocer74** [comment]
Готово !

**Comment by artembeloglazov** [comment]
После закрытия задачи https://github.com/rg1ru/obsada-front/issues/23 эта ошибка вернулась

**Comment by artembeloglazov** [comment]
- [ ] исправить отображение кнопки под windows в internet explorer

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/861680/40892054-ed984c42-6799-11e8-9a6c-6695bf688932.png">

**Comment by artembeloglazov** [comment]
### на айфоне кнопка частично скрыта

![f292db0d-8aea-4372-9f68-31ef41982686](https://user-images.githubusercontent.com/861680/40992617-f79d07b6-68ff-11e8-9a63-68c3eea3cd3b.png)
